#encoding: utf-8

Person.delete_all

[
{ :f_name => ' Grace', :l_name => 'Forsyth', :email => 'grace.forsyth@mycompany', :age => 66, :city => 'Fairfax', :state => 'GA', :zip => '42161' },
{ :f_name => ' Simon', :l_name => 'Taylor', :email => 'simon.taylor@mycompany', :age => 51, :city => 'Duarte', :state => 'ID', :zip => '84826' },
{ :f_name => ' Lucas', :l_name => 'Thomson', :email => 'lucas.thomson@mycompany', :age => 64, :city => 'Beverly', :state => 'ID', :zip => '95506' },
{ :f_name => ' Sonia', :l_name => 'Fraser', :email => 'sonia.fraser@mycompany', :age => 68, :city => 'Ponce', :state => 'FL', :zip => '40194' },
{ :f_name => ' Dan', :l_name => 'Hamilton', :email => 'dan.hamilton@mycompany', :age => 40, :city => 'La Palma', :state => 'CO', :zip => '33862' },
{ :f_name => ' Grace', :l_name => 'Dowd', :email => 'grace.dowd@mycompany', :age => 50, :city => 'El Paso', :state => 'NH', :zip => '66016' },
{ :f_name => ' Una', :l_name => 'Lawrence', :email => 'una.lawrence@mycompany', :age => 64, :city => 'Norwich', :state => 'OH', :zip => '49153' },
{ :f_name => ' Sam', :l_name => 'MacDonald', :email => 'sam.macdonald@mycompany', :age => 74, :city => 'DeKalb', :state => 'PA', :zip => '24887' },
{ :f_name => ' Penelope', :l_name => 'Fisher', :email => 'penelope.fisher@mycompany', :age => 72, :city => 'Duquesne', :state => 'ND', :zip => '90986' },
{ :f_name => ' Robert', :l_name => 'Peake', :email => 'robert.peake@mycompany', :age => 67, :city => 'Narragansett', :state => 'VA', :zip => '55089' },
{ :f_name => ' Rebecca', :l_name => 'Simpson', :email => 'rebecca.simpson@mycompany', :age => 56, :city => 'Waycross', :state => 'WI', :zip => '12694' },
{ :f_name => ' Lisa', :l_name => 'Lee', :email => 'lisa.lee@mycompany', :age => 56, :city => 'Carson', :state => 'PA', :zip => '00449' },
{ :f_name => ' Gordon', :l_name => 'Bower', :email => 'gordon.bower@mycompany', :age => 74, :city => 'Kearney', :state => 'LA', :zip => '97922' },
{ :f_name => ' Stephanie', :l_name => 'Mitchell', :email => 'stephanie.mitchell@mycompany', :age => 48, :city => 'Lomita', :state => 'IN', :zip => '20952' },
{ :f_name => ' Harry', :l_name => 'Wilson', :email => 'harry.wilson@mycompany', :age => 36, :city => 'DeKalb', :state => 'IL', :zip => '49039' },
{ :f_name => ' Penelope', :l_name => 'Hamilton', :email => 'penelope.hamilton@mycompany', :age => 54, :city => 'Biddeford', :state => 'OR', :zip => '17837' },
{ :f_name => ' Samantha', :l_name => 'Davidson', :email => 'samantha.davidson@mycompany', :age => 22, :city => 'Morrison', :state => 'IN', :zip => '72925' },
{ :f_name => ' Hannah', :l_name => 'Kerr', :email => 'hannah.kerr@mycompany', :age => 27, :city => 'Asheville', :state => 'GA', :zip => '43417' },
{ :f_name => ' Carl', :l_name => 'Mackay', :email => 'carl.mackay@mycompany', :age => 80, :city => 'Houma', :state => 'GA', :zip => '28739' },
{ :f_name => ' Natalie', :l_name => 'Coleman', :email => 'natalie.coleman@mycompany', :age => 69, :city => 'Long Beach', :state => 'HI', :zip => '86264' },
{ :f_name => ' Melanie', :l_name => 'Miller', :email => 'melanie.miller@mycompany', :age => 39, :city => 'Melrose', :state => 'NY', :zip => '68192' },
{ :f_name => ' Kevin', :l_name => 'Murray', :email => 'kevin.murray@mycompany', :age => 77, :city => 'Marietta', :state => 'MI', :zip => '86319' },
{ :f_name => ' Brian', :l_name => 'Cameron', :email => 'brian.cameron@mycompany', :age => 26, :city => 'Cumberland', :state => 'VA', :zip => '44562' },
{ :f_name => ' Blake', :l_name => 'Lewis', :email => 'blake.lewis@mycompany', :age => 50, :city => 'Burbank', :state => 'WA', :zip => '45152' },
{ :f_name => ' Eric', :l_name => 'Payne', :email => 'eric.payne@mycompany', :age => 28, :city => 'Aliquippa', :state => 'OR', :zip => '26755' },
{ :f_name => ' Jane', :l_name => 'Greene', :email => 'jane.greene@mycompany', :age => 80, :city => 'Geneva', :state => 'WV', :zip => '16430' },
{ :f_name => ' Joseph', :l_name => 'MacLeod', :email => 'joseph.macleod@mycompany', :age => 25, :city => 'West Warwick', :state => 'UT', :zip => '06151' },
{ :f_name => ' Dominic', :l_name => 'Langdon', :email => 'dominic.langdon@mycompany', :age => 68, :city => 'Saginaw', :state => 'OH', :zip => '74296' },
{ :f_name => ' Dylan', :l_name => 'Ellison', :email => 'dylan.ellison@mycompany', :age => 53, :city => 'Vancouver', :state => 'OH', :zip => '01123' },
{ :f_name => ' Fiona', :l_name => 'Mackay', :email => 'fiona.mackay@mycompany', :age => 49, :city => 'Provo', :state => 'PA', :zip => '75495' },
{ :f_name => ' Katherine', :l_name => 'Greene', :email => 'katherine.greene@mycompany', :age => 26, :city => 'Burlington', :state => 'DE', :zip => '97994' },
{ :f_name => ' Alison', :l_name => 'Sanderson', :email => 'alison.sanderson@mycompany', :age => 67, :city => 'Grand Forks', :state => 'GA', :zip => '11252' },
{ :f_name => ' Molly', :l_name => 'Jones', :email => 'molly.jones@mycompany', :age => 53, :city => 'Houma', :state => 'ND', :zip => '42319' },
{ :f_name => ' Ava', :l_name => 'Kelly', :email => 'ava.kelly@mycompany', :age => 44, :city => 'West Memphis', :state => 'NY', :zip => '70600' },
{ :f_name => ' Madeleine', :l_name => 'Jones', :email => 'madeleine.jones@mycompany', :age => 41, :city => 'Haverhill', :state => 'WV', :zip => '31333' },
{ :f_name => ' Nicola', :l_name => 'Poole', :email => 'nicola.poole@mycompany', :age => 43, :city => 'Lawrence', :state => 'NV', :zip => '95169' },
{ :f_name => ' Tracey', :l_name => 'Hemmings', :email => 'tracey.hemmings@mycompany', :age => 62, :city => 'Jeannette', :state => 'AK', :zip => '07355' },
{ :f_name => ' Andrea', :l_name => 'Butler', :email => 'andrea.butler@mycompany', :age => 20, :city => 'Jordan Valley', :state => 'DE', :zip => '55438' },
{ :f_name => ' Olivia', :l_name => 'Morrison', :email => 'olivia.morrison@mycompany', :age => 69, :city => 'North Adams', :state => 'ND', :zip => '16886' },
{ :f_name => ' Joshua', :l_name => 'Buckland', :email => 'joshua.buckland@mycompany', :age => 36, :city => 'Jefferson City', :state => 'AZ', :zip => '43584' },
{ :f_name => ' Matt', :l_name => 'Ogden', :email => 'matt.ogden@mycompany', :age => 62, :city => 'Great Falls', :state => 'GA', :zip => '60416' },
{ :f_name => ' Joe', :l_name => 'Grant', :email => 'joe.grant@mycompany', :age => 35, :city => 'Annapolis', :state => 'NV', :zip => '16018' },
{ :f_name => ' Thomas', :l_name => 'Ferguson', :email => 'thomas.ferguson@mycompany', :age => 61, :city => 'Plantation', :state => 'AL', :zip => '47682' },
{ :f_name => ' Andrew', :l_name => 'Bower', :email => 'andrew.bower@mycompany', :age => 53, :city => 'Bakersfield', :state => 'MD', :zip => '73469' },
{ :f_name => ' Cameron', :l_name => 'Mackay', :email => 'cameron.mackay@mycompany', :age => 65, :city => 'Layton', :state => 'DC', :zip => '16008' },
{ :f_name => ' Connor', :l_name => 'Lawrence', :email => 'connor.lawrence@mycompany', :age => 56, :city => 'Reno', :state => 'AZ', :zip => '70214' },
{ :f_name => ' Emma', :l_name => 'Hill', :email => 'emma.hill@mycompany', :age => 70, :city => 'Bangor', :state => 'SC', :zip => '87424' },
{ :f_name => ' Angela', :l_name => 'Powell', :email => 'angela.powell@mycompany', :age => 25, :city => 'Reading', :state => 'OH', :zip => '13824' },
{ :f_name => ' Molly', :l_name => 'Piper', :email => 'molly.piper@mycompany', :age => 71, :city => 'La Mirada', :state => 'LA', :zip => '15363' },
{ :f_name => ' Samantha', :l_name => 'Grant', :email => 'samantha.grant@mycompany', :age => 58, :city => 'Goose Creek', :state => 'WY', :zip => '02130' },
{ :f_name => ' Andrea', :l_name => 'Walsh', :email => 'andrea.walsh@mycompany', :age => 55, :city => 'South Gate', :state => 'PA', :zip => '40422' },
{ :f_name => ' Lisa', :l_name => 'Wright', :email => 'lisa.wright@mycompany', :age => 33, :city => 'Salem', :state => 'AL', :zip => '49870' },
{ :f_name => ' Dan', :l_name => 'Clarkson', :email => 'dan.clarkson@mycompany', :age => 52, :city => 'Highland Park', :state => 'CO', :zip => '46127' },
{ :f_name => ' Ian', :l_name => 'Dickens', :email => 'ian.dickens@mycompany', :age => 52, :city => 'Kenner', :state => 'ME', :zip => '28953' },
{ :f_name => ' Samantha', :l_name => 'Marshall', :email => 'samantha.marshall@mycompany', :age => 64, :city => 'Whittier', :state => 'AK', :zip => '85700' },
{ :f_name => ' Bella', :l_name => 'Anderson', :email => 'bella.anderson@mycompany', :age => 40, :city => 'Ogden', :state => 'VT', :zip => '29303' },
{ :f_name => ' Keith', :l_name => 'Manning', :email => 'keith.manning@mycompany', :age => 59, :city => 'Barrow', :state => 'GA', :zip => '60812' },
{ :f_name => ' Ella', :l_name => 'Duncan', :email => 'ella.duncan@mycompany', :age => 74, :city => 'Palmdale', :state => 'CA', :zip => '08426' },
{ :f_name => ' David', :l_name => 'Wallace', :email => 'david.wallace@mycompany', :age => 23, :city => 'Albuquerque', :state => 'AK', :zip => '66838' },
{ :f_name => ' Emma', :l_name => 'Mills', :email => 'emma.mills@mycompany', :age => 43, :city => 'Providence', :state => 'OK', :zip => '71757' },
{ :f_name => ' Gordon', :l_name => 'Brown', :email => 'gordon.brown@mycompany', :age => 74, :city => 'Powell', :state => 'MA', :zip => '00700' },
{ :f_name => ' Melanie', :l_name => 'Buckland', :email => 'melanie.buckland@mycompany', :age => 49, :city => 'New Kensington', :state => 'NV', :zip => '53050' },
{ :f_name => ' Andrea', :l_name => 'Hill', :email => 'andrea.hill@mycompany', :age => 57, :city => 'Normal', :state => 'MD', :zip => '11428' },
{ :f_name => ' Kevin', :l_name => 'Smith', :email => 'kevin.smith@mycompany', :age => 40, :city => 'Manitowoc', :state => 'VA', :zip => '68269' },
{ :f_name => ' Sally', :l_name => 'Black', :email => 'sally.black@mycompany', :age => 31, :city => 'Downey', :state => 'ME', :zip => '05621' },
{ :f_name => ' Isaac', :l_name => 'Powell', :email => 'isaac.powell@mycompany', :age => 27, :city => 'Aspen', :state => 'IN', :zip => '90442' },
{ :f_name => ' Steven', :l_name => 'Morgan', :email => 'steven.morgan@mycompany', :age => 22, :city => 'Moraga', :state => 'VT', :zip => '43869' },
{ :f_name => ' Gabrielle', :l_name => 'Harris', :email => 'gabrielle.harris@mycompany', :age => 59, :city => 'Plattsburgh', :state => 'VA', :zip => '19649' },
{ :f_name => ' Deirdre', :l_name => 'Thomson', :email => 'deirdre.thomson@mycompany', :age => 54, :city => 'Citrus Heights', :state => 'CT', :zip => '15924' },
{ :f_name => ' Dorothy', :l_name => 'Murray', :email => 'dorothy.murray@mycompany', :age => 64, :city => 'Bay St. Louis', :state => 'PA', :zip => '38672' },
{ :f_name => ' Sophie', :l_name => 'Pullman', :email => 'sophie.pullman@mycompany', :age => 41, :city => 'Aspen', :state => 'NC', :zip => '38699' },
{ :f_name => ' Dan', :l_name => 'Butler', :email => 'dan.butler@mycompany', :age => 63, :city => 'Moore', :state => 'NM', :zip => '76807' },
{ :f_name => ' Caroline', :l_name => 'Wallace', :email => 'caroline.wallace@mycompany', :age => 29, :city => 'Greensburg', :state => 'AZ', :zip => '17731' },
{ :f_name => ' Jane', :l_name => 'Taylor', :email => 'jane.taylor@mycompany', :age => 26, :city => 'Mesquite', :state => 'CA', :zip => '15619' },
{ :f_name => ' Adam', :l_name => 'Reid', :email => 'adam.reid@mycompany', :age => 34, :city => 'Marshfield', :state => 'PA', :zip => '35083' },
{ :f_name => ' Maria', :l_name => 'Johnston', :email => 'maria.johnston@mycompany', :age => 48, :city => 'New Brunswick', :state => 'OH', :zip => '04485' },
{ :f_name => ' Lauren', :l_name => 'Langdon', :email => 'lauren.langdon@mycompany', :age => 26, :city => 'Douglas', :state => 'NY', :zip => '10291' },
{ :f_name => ' Adrian', :l_name => 'Grant', :email => 'adrian.grant@mycompany', :age => 69, :city => 'Seward', :state => 'NC', :zip => '10673' },
{ :f_name => ' Faith', :l_name => 'Ross', :email => 'faith.ross@mycompany', :age => 61, :city => 'Covina', :state => 'OR', :zip => '39970' },
{ :f_name => ' Jasmine', :l_name => 'Duncan', :email => 'jasmine.duncan@mycompany', :age => 58, :city => 'Holyoke', :state => 'FL', :zip => '45977' },
{ :f_name => ' Connor', :l_name => 'Reid', :email => 'connor.reid@mycompany', :age => 72, :city => 'Waterloo', :state => 'AZ', :zip => '83465' },
{ :f_name => ' Anthony', :l_name => 'North', :email => 'anthony.north@mycompany', :age => 59, :city => 'Ketchikan', :state => 'IA', :zip => '50103' },
{ :f_name => ' Paul', :l_name => 'Dickens', :email => 'paul.dickens@mycompany', :age => 78, :city => 'Benton Harbor', :state => 'WI', :zip => '33037' },
{ :f_name => ' Christopher', :l_name => 'Hardacre', :email => 'christopher.hardacre@mycompany', :age => 58, :city => 'Miami Beach', :state => 'HI', :zip => '15924' },
{ :f_name => ' Madeleine', :l_name => 'Metcalfe', :email => 'madeleine.metcalfe@mycompany', :age => 25, :city => 'Gary', :state => 'ND', :zip => '14199' },
{ :f_name => ' Paul', :l_name => 'Hill', :email => 'paul.hill@mycompany', :age => 75, :city => 'Clemson', :state => 'AK', :zip => '19622' },
{ :f_name => ' Joshua', :l_name => 'Harris', :email => 'joshua.harris@mycompany', :age => 56, :city => 'Woodward', :state => 'IL', :zip => '88210' },
{ :f_name => ' Isaac', :l_name => 'McLean', :email => 'isaac.mclean@mycompany', :age => 39, :city => 'Stanton', :state => 'CA', :zip => '49421' },
{ :f_name => ' Richard', :l_name => 'Ross', :email => 'richard.ross@mycompany', :age => 67, :city => 'Slidell', :state => 'MN', :zip => '61612' },
{ :f_name => ' Paul', :l_name => 'Henderson', :email => 'paul.henderson@mycompany', :age => 50, :city => 'Muskegon', :state => 'TX', :zip => '88456' },
{ :f_name => ' Stewart', :l_name => 'Chapman', :email => 'stewart.chapman@mycompany', :age => 23, :city => 'Gloversville', :state => 'TX', :zip => '78602' },
{ :f_name => ' Stephen', :l_name => 'Graham', :email => 'stephen.graham@mycompany', :age => 51, :city => 'Nome', :state => 'MS', :zip => '30806' },
{ :f_name => ' Max', :l_name => 'Greene', :email => 'max.greene@mycompany', :age => 41, :city => 'Wausau', :state => 'PA', :zip => '37725' },
{ :f_name => ' Thomas', :l_name => 'Chapman', :email => 'thomas.chapman@mycompany', :age => 55, :city => 'Mission Viejo', :state => 'OK', :zip => '09946' },
{ :f_name => ' Una', :l_name => 'Hughes', :email => 'una.hughes@mycompany', :age => 49, :city => 'Scranton', :state => 'CA', :zip => '72645' },
{ :f_name => ' Samantha', :l_name => 'Bower', :email => 'samantha.bower@mycompany', :age => 61, :city => 'Pine Bluff', :state => 'IL', :zip => '23247' },
{ :f_name => ' Jake', :l_name => 'Gray', :email => 'jake.gray@mycompany', :age => 44, :city => 'Weirton', :state => 'GA', :zip => '76697' },
{ :f_name => ' Dominic', :l_name => 'Ellison', :email => 'dominic.ellison@mycompany', :age => 49, :city => 'Nichols Hills', :state => 'WV', :zip => '72089' },
{ :f_name => ' Jennifer', :l_name => 'Ross', :email => 'jennifer.ross@mycompany', :age => 52, :city => 'El Cerrito', :state => 'NE', :zip => '26468' },
{ :f_name => ' Mary', :l_name => 'Scott', :email => 'mary.scott@mycompany', :age => 70, :city => 'Rolla', :state => 'TN', :zip => '75323' }].each do |record|
	Person.create(record)
end
